//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Capitole: BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Capitole()
        {
            this.Intrebaris = new HashSet<Intrebari>();
        }
    
        [DataMember]
        public int IdCapitol { get; set; }
        [DataMember]
        public string NumeCapitol { get; set; }
        [DataMember]
        public int DisciplinaIdDisciplina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Intrebari> Intrebaris { get; set; }
        [DataMember]
        public virtual Disciplina Disciplina { get; set; }
    }
}
