//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Intrebari: BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Intrebari()
        {
            this.IntrebariTestes = new HashSet<IntrebariTeste>();
            this.Raspunsuris = new HashSet<Raspunsuri>();
            this.TesteSalvateInBazaDeDates = new HashSet<TesteSalvateInBazaDeDate>();
        }

        [DataMember]
        public int IdIntrebare { get; set; }
        [DataMember]
        public string Intrebarea { get; set; }
        [DataMember]
        public int CapitoleIdCapitol { get; set; }

        [DataMember]
        public virtual Capitole Capitole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<IntrebariTeste> IntrebariTestes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [DataMember]
        public virtual ICollection<Raspunsuri> Raspunsuris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<TesteSalvateInBazaDeDate> TesteSalvateInBazaDeDates { get; set; }
    }
}
