//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class Lectori: BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lectori()
        {
            this.TestCreatDeLectors = new HashSet<TestCreatDeLector>();
        }

        [DataMember]
        public int IdLector { get; set; }
        [DataMember]
        public string ContLector { get; set; }
        [DataMember]
        public string Parola { get; set; }
        [DataMember]
        public int DisciplinaIdDisciplina { get; set; }

        [DataMember]
        public virtual Disciplina Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<TestCreatDeLector> TestCreatDeLectors { get; set; }
    }
}
