//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference = true)]
    public partial class ListaCursantiTestProgramat: BaseEntity
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public int ProgramareTestId { get; set; }
        [DataMember]
        public int CursantiIdCursant { get; set; }

        [DataMember]
        public virtual Cursanti Cursanti { get; set; }
        [DataMember]
        public virtual ProgramareTest ProgramareTest { get; set; }
    }
}
